In [1]:
import numpy as np

## Initialization

In [2]:
def matrix_ini():
    m = int(input("Enter the number of rows:")) 
    n = int(input("Enter the number of columns:")) 
    
    print("Enter the entries of matrix in single line, separated by space: ")
    elements = list(map(float, input().split()))
    matrix = np.array(elements).reshape(m, n) 
    print(matrix,'\n') 
    
    return matrix

In [3]:
def m_mul(a,b):
    mul = np.zeros((len(a[0]),len(b)))
    for i in range(len(a)): 
        for j in range(len(b[0])): 
            for k in range(len(b)): 
                mul[i][j] += a[i][k] * b[k][j] 
    return mul

In [4]:
def lu_decom(mat , n):
    lower = [[0 for x in range(n)]for y in range(n)]
    upper = [[0 for x in range(n)]for y in range(n)]
    p = np.eye(n, dtype=np.double)
    
    for i in range(n):
 
        # Upper Triangular
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])
            upper[i][k] = mat[i][k] - sum
 
        # Lower Triangular
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  # Diagonal as 1
            else:
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])
                lower[k][i] = ((mat[k][i] - sum) /upper[i][i])
        
    lower = np.reshape(lower,(n,n))
    upper = np.reshape(upper,(n,n))
    p = np.reshape(p,(n,n))
    
    return lower, upper,p

In [5]:
def forward_substitution(L, b):
    
    #Get number of rows
    n = L.shape[0]
    
    #Allocating space for the solution vector
    y = np.zeros_like(b, dtype=np.double);
    
    #Here we perform the forward-substitution.  
    #Initializing  with the first row.
    y[0] = b[0] / L[0, 0]
    
    #Looping over rows in reverse (from the bottom  up),
    #starting with the second to last row, because  the 
    #last row solve was completed in the last step.
    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]
        
    return y

In [6]:
def back_substitution(U, y):
    
    #Number of rows
    n = U.shape[0]
    
    #Allocating space for the solution vector
    x = np.zeros_like(y, dtype=np.double);

    #Here we perform the back-substitution.  
    #Initializing with the last row.
    x[-1] = y[-1] / U[-1, -1]
    
    #Looping over rows in reverse (from the bottom up), 
    #starting with the second to last row, because the 
    #last row solve was completed in the last step.
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]
        
    return x

In [7]:
def plu_inverse(A):
    n = A.shape[0]
    
    b = np.eye(n)
    Ainv = np.zeros((n, n))
    
    L, U, P = lu_decom(A,n)
    
    for i in range(n):
        
        y = forward_substitution(L, np.dot(P, b[i, :]))
        
        Ainv[i, :] = back_substitution(U, y)
        
    return Ainv

## Execution:

In [8]:
mat = matrix_ini()

Enter the number of rows:3
Enter the number of columns:3
Enter the entries of matrix in single line, separated by space: 
15 -3 -1 -3 18 -6 -4 -1 12
[[15. -3. -1.]
 [-3. 18. -6.]
 [-4. -1. 12.]] 



In [9]:
L,U,P = lu_decom(mat,len(mat))

In [10]:
mat_in_T = plu_inverse(mat)

In [11]:
mat_in = np.zeros((len(mat),len(mat)))
for i in range(len(mat)):
   # iterate through columns
   for j in range(len(mat[0])):
        mat_in[j][i] = mat_in_T[i][j]

In [12]:
# Check:
print(mat_in.all() == np.linalg.inv(mat).all())

True


## Result:

In [13]:
print('Original matrix:\n',mat,'\n Upper matrix:\n',U,'\n Lower matrix:\n', L , '\n Inverse matrix:\n', mat_in)

Original matrix:
 [[15. -3. -1.]
 [-3. 18. -6.]
 [-4. -1. 12.]] 
 Upper matrix:
 [[15.         -3.         -1.        ]
 [ 0.         17.4        -6.2       ]
 [ 0.          0.         11.09195402]] 
 Lower matrix:
 [[ 1.          0.          0.        ]
 [-0.2         1.          0.        ]
 [-0.26666667 -0.10344828  1.        ]] 
 Inverse matrix:
 [[0.07253886 0.01278066 0.01243523]
 [0.02072539 0.06079447 0.03212435]
 [0.02590674 0.00932642 0.09015544]]
